config/routes.rb
Rails.application.routes.draw do 
  resources :ql_truongs
  get 'admin/dashboard'
   
  root  'static_pages#home'   
  get 'help'=> 'static_pages#help'
  get 'signup'  => 'users#new'
  get 'admin'  => 'admin#dashboard'
  
   
  resources :sessions, only: [:new, :create, :destroy] 
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ql_truong.rb
class QlTruong < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to "/login"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ql_truongs_controller.rb
class QlTruongsController < ApplicationController
  before_action :set_ql_truong, only: %i[ show edit update destroy ]

  # GET /ql_truongs or /ql_truongs.json
  def index
    @ql_truongs = QlTruong.all
  end

  # GET /ql_truongs/1 or /ql_truongs/1.json
  def show
  end

  # GET /ql_truongs/new
  def new
    @ql_truong = QlTruong.new
  end

  # GET /ql_truongs/1/edit
  def edit
  end

  # POST /ql_truongs or /ql_truongs.json
  def create
    @ql_truong = QlTruong.new(ql_truong_params)

    respond_to do |format|
      if @ql_truong.save
        format.html { redirect_to ql_truong_url(@ql_truong), notice: "Ql truong was successfully created." }
        format.json { render :show, status: :created, location: @ql_truong }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ql_truong.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ql_truongs/1 or /ql_truongs/1.json
  def update
    respond_to do |format|
      if @ql_truong.update(ql_truong_params)
        format.html { redirect_to ql_truong_url(@ql_truong), notice: "Ql truong was successfully updated." }
        format.json { render :show, status: :ok, location: @ql_truong }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ql_truong.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ql_truongs/1 or /ql_truongs/1.json
  def destroy
    @ql_truong.destroy

    respond_to do |format|
      format.html { redirect_to ql_truongs_url, notice: "Ql truong was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ql_truong
      @ql_truong = QlTruong.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ql_truong_params
      params.require(:ql_truong).permit(:ten, :chuyen_nganh, :vi_tri, :thoi_gian_hd, :sl_hoc_sinh, :nganh_dt)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    
    if user.present? && params[:password] 
      session[:user_id] = user.id
      if user.status === 0
        redirect_to "/users"
      else
        redirect_to "/users"
      end
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if session[:user_id]
      @user = User.find_by(id: session[:user_id])
    else
      redirect_to "/login"
    end
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :roles, :status)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ql_truongs_helper.rb
module QlTruongsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
      def log_in(user)
            session[:user_id] = user.id
      end

      def current_user
            @current_user ||= User.find_by(id: session[:user_id])
      end

      def logged_in?
            !current_user.nil?
      end

      def log_out
            session.delete(:user_id)
            @current_user = nil
          end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">NavBar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li><%= link_to "User",   'users' %></li>
        <li class="linkNav"><%= link_to "School",   'ql_truongs' %></li>
      </ul>
    </div>
    <div>
        <% if current_user %>
          Logged in as <%= current_user.name %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
          <%= link_to "Sign Up", signup_path %> or
          <%= link_to "Log In", login_path %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cuoiky</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
      <%= render 'layouts/header' %>
    <%= yield %>
    
  </body>
</html>

app/views/ql_truongs/_form.html.erb
<%= form_with(model: ql_truong) do |form| %>
  <% if ql_truong.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ql_truong.errors.count, "error") %> prohibited this ql_truong from being saved:</h2>

      <ul>
        <% ql_truong.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ten, style: "display: block" %>
    <%= form.text_field :ten %>
  </div>

  <div>
    <%= form.label :chuyen_nganh, style: "display: block" %>
    <%= form.text_field :chuyen_nganh %>
  </div>

  <div>
    <%= form.label :vi_tri, style: "display: block" %>
    <%= form.text_field :vi_tri %>
  </div>

  <div>
    <%= form.label :thoi_gian_hd, style: "display: block" %>
    <%= form.date_field :thoi_gian_hd %>
  </div>

  <div>
    <%= form.label :sl_hoc_sinh, style: "display: block" %>
    <%= form.number_field :sl_hoc_sinh %>
  </div>

  <div>
    <%= form.label :nganh_dt, style: "display: block" %>
    <%= form.text_field :nganh_dt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ql_truongs/_ql_truong.html.erb
<div id="<%= dom_id ql_truong %>">
  <p>
    <strong>Ten:</strong>
    <%= ql_truong.ten %>
  </p>

  <p>
    <strong>Chuyen nganh:</strong>
    <%= ql_truong.chuyen_nganh %>
  </p>

  <p>
    <strong>Vi tri:</strong>
    <%= ql_truong.vi_tri %>
  </p>

  <p>
    <strong>Thoi gian hd:</strong>
    <%= ql_truong.thoi_gian_hd %>
  </p>

  <p>
    <strong>Sl hoc sinh:</strong>
    <%= ql_truong.sl_hoc_sinh %>
  </p>

  <p>
    <strong>Nganh dt:</strong>
    <%= ql_truong.nganh_dt %>
  </p>

</div>

app/views/ql_truongs/edit.html.erb
<h1>Editing ql truong</h1>

<%= render "form", ql_truong: @ql_truong %>

<br>

<div>
  <%= link_to "Show this ql truong", @ql_truong %> |
  <%= link_to "Back to ql truongs", ql_truongs_path %>
</div>

app/views/ql_truongs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ql truongs</h1>

<div id="ql_truongs">
  <% @ql_truongs.each do |ql_truong| %>
    <%= render ql_truong %>
    <p>
      <%= link_to "Show this ql truong", ql_truong %>
    </p>
  <% end %>
</div>

<%= link_to "New ql truong", new_ql_truong_path %>

app/views/ql_truongs/new.html.erb
<h1>School</h1>

<%= render "form", ql_truong: @ql_truong %>

<br>

<div>
  <%= link_to "Back to ql truongs", ql_truongs_path %>
</div>

app/views/ql_truongs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ql_truong %>

<div>
  <%= link_to "Edit this ql truong", edit_ql_truong_path(@ql_truong) %> |
  <%= link_to "Back to school", ql_truongs_path %>

  <%= button_to "Destroy this ql truong", @ql_truong, method: :delete %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<%= @user.name %>

app/views/users/_form.html.erb
<div class="logout-form">
  <%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bg-login-field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="bg-login-field">
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div class="bg-login-field">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="bg-login-field">
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div class="bg-login-field">
    <%= form.label :roles, style: "display: block" %>
    <%= form.number_field :roles %>
  </div>

  <div class="bg-login-field">
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div class="logout-btn">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Roles:</strong>
    <%= user.roles %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= user.status %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>List Users</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Show</th>
      <th scope="col">Update</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody> 
    <% @users.each_with_index do |user| %>
      <tr>
    
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete,
                                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %> 
  <tbody> 
</table>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="bg-logout">
  <div class="bg-logout-content">
      <h1 class="bg-logout-title">New user</h1>
      <div>
        <%= render "form", user: @user %>
      <div>
        <%= link_to "Back to users", users_path %>
      </div>
      </div>
  <div>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>